config/routes.rb
Tcoc::Application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :articles
    resources :categories
    resources :pages
  end
  match 'pages/:slug' => 'pages#show'
  resources :pages
  resources :articles
  match 'categories/:slug' => 'categories#show'
  resources :categories

  root :to => "articles#index"

end

app/views/admin/pages/_form.html.erb
<%= f.input :title %>
<%= f.input :slug %>
<%= f.input :parent %>
<%= f.input :context %>
<%= f.input :excerpt_image %>
<%= f.submit %>

<script type="text/javascript">
  $(function() {
    $('#page_context').tinymce({
      theme: 'advanced'
    });
  });
</script>

app/views/admin/pages/edit.html.erb
<h1>Edit Pages</h1>
<%= simple_form_for @page , :url => admin_page_path(@page) , :html => { :multipart => true } do |f|  %>
<%= render :partial => 'form' , :locals => { :f => f} %>
<% end %>

app/views/admin/pages/index.html.erb
<h1>page list</h1>
<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th
    </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %>
    <td><%= link_to 'Show' , page_path(page.slug) %></td>
    <td><%= link_to 'Edit' , edit_admin_page_path(page) %></td>
    <td><%= link_to 'Destory', admin_page_path(page) , :confirm => 'Are you sure?' , :method => 'delete' %></td>
  </tr>
<% end %>
</table>
<%= will_paginate(@pages) %>
<%= link_to 'New Page' , new_admin_page_path %>

app/views/admin/pages/new.html.erb
<h1>create Page</h1>
<%= simple_form_for @page , :url => admin_pages_path ,:html => { :multipart => true} do |f| %>
  <%= render :partial => 'form' , :locals => { :f => f} %>
<% end %>