config/routes.rb
Tcoc::Application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :articles
    resources :categories
    resources :pages
  end
  match 'pages/:slug' => 'pages#show'
  resources :pages
  resources :articles
  match 'categories/:slug' => 'categories#show'
  resources :categories

  root :to => "articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categoryships
  has_many :categories, :through => :article_categoryships, :dependent => :destroy
  has_attached_file :excerpt_image, :styles => { :medium => "300x300" , :thumb => "100x100"},
    :path => ":rails_root/public/images/article/:attachment/:id/:basename-:style.:extension",
     :url => "/images/article/:attachment/:id/:basename-:style.:extension"
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout 'admin'
  before_filter :require_is_admin
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(:page => params[:page] ,:per_page => 20 )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_article_path(@article), :notice => 'Article was successfully created.' }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to admin_article_path(@article), :notice => 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, :notice => 'Article was successfully created.' }
        format.json { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, :notice => 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article , :html => { :multipart => true } do |f| %>
<%= f.input :Title %>
<%= f.input :Slug %>
<%= f.input :Description %>
<%= f.input :Post_type %>
<%= f.input :Post_status %>
<%= f.input :Post_date %>
<%= f.input :hit_count %>
<%= f.input :Content, :input_html => { :class => 'tb_Content'} %>
<%= f.input :excerpt_image %>
<script type="text/javascript">
  $(function() {
    $('#article_Content').tinymce({
      theme: 'simple'
    });
  });
</script>

<%= f.submit %>

<% end %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Post date</th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= link_to  article.Title , article %></td>
    <td><%= article.Post_date %></td>
  </tr>
<% end %>
</table>
<%= will_paginate(@articles) %>
<br />
<% if current_user && current_user.is_admin? %>
  <%= link_to 'New Article', new_admin_article_path %>
<% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.Title %>
</p>

<p>
  <b>Slug:</b>
  <%= @article.Slug %>
</p>

<p>
  <b>Description:</b>
  <%= @article.Description %>
</p>

<p>
  <b>Content:</b>
  <%= @article.Content %>
</p>

<p>
  <b>Post type:</b>
  <%= @article.Post_type %>
</p>

<p>
  <b>Post status:</b>
  <%= @article.Post_status %>
</p>

<p>
  <b>Post date:</b>
  <%= @article.Post_date %>
</p>

<p>
  <b>Hit count:</b>
  <%= @article.hit_count %>
</p>
<% if @article.excerpt_image %>
<p>
  <%= image_tag @article.excerpt_image.url(:medium) %>
</p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>