config/routes.rb
Tcoc::Application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :articles
    resources :categories
    resources :pages
  end
  match 'pages/:slug' => 'pages#show'
  resources :pages
  resources :articles
  match 'categories/:slug' => 'categories#show'
  resources :categories

  root :to => "articles#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categoryship
  has_many :article ,:through => :article_categoryship, :dependent => :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	layout 'admin'
  before_filter :require_is_admin
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, :notice => 'Category was successfully created.' }
        format.json { render :json => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to admin_categories_path, :notice => 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :ok }
    end
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    #@category = Category.all( :conditions => [ "name = ?" , params[:slug]]).first
    #@article = @category.article
    @category = Category.where(["slug = ?",params[:slug]]).first
    @articles = @category.article.paginate(:page => params[:page], :per_page => 5)
    #@articles= Article.all(:joins => :categories, :conditions => { :categories => { :slug => params[:slug]}})
    if @articles.count == 0
      redirect_to categories_path
    else

    respond_to do |format|
       format.html # show.html.erb
      format.json { render :json => @article }
    end
    end

  end
  def index
    @categories = Category.all
    respond_to do |format|
      format.html
      format.json {render :json => @categories}
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>Listing category</h1>

<table>
  <tr>
    <th>Title</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.name , category_path(category.slug) %></td>
</tr>
<% end %>
</table>

app/views/categories/show.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Slug</th>
    <th>Description</th>
    <th>Content</th>
    <th>Post type</th>
    <th>Post status</th>
    <th>Post date</th>
    <th>Hit count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.Title %></td>
    <td><%= article.Slug %></td>
    <td><%= article.Description %></td>
    <td><%= article.Content %></td>
    <td><%= article.Post_type %></td>
    <td><%= article.Post_status %></td>
    <td><%= article.Post_date %></td>
    <td><%= article.hit_count %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_admin_article_path(article) %></td>
    <td><%= link_to 'Destroy', admin_article_path(article), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate(@articles) %>
<br />